name: Flight Price Check

on:
  schedule:
  - cron: '*/15 * * * *'
 # workflow_dispatch:    # Allows manual trigger

jobs:
  check-flight:
    runs-on: ubuntu-latest
    env:
      RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run flight price script
        run: python flight_check.py
